# Copy this file to secrets.yml, and CHANGE THESE TOKENS to a random string
# Of your own choosing! (DO NOT directly copy these - this is a security risk!!)

development:
  secret_token: "my_secret_token"
  secret_key_base: "abcdef0123456789"

test:
  secret_token: "my_secret_token"
  secret_key_base: "abcdef0123456789"

